"""Synthetic EEG with chosen ground truth, for the muse-stage tests.

Deliberately not imported from ~/projects/muse: these tests exercise the
adapters, and a test signal generated by the same project's own synthetic
module would hide an orientation or scaling mistake at the boundary. Returns
(channels, samples), muse's orientation — the adapters transpose.
"""

import numpy as np

FS = 256.0
CHANNELS = ("TP9", "AF7", "AF8", "TP10")


def synth(dur=30.0, alpha=12.0, beta=4.0, asym=0.0, emg=0.0, noise=5.0, seed=0,
          emg_bursts=()):
    """`emg` is SUSTAINED frontal muscle, `emg_bursts` is a list of
    (start_s, dur_s, amplitude_uv) short-lived ones. The distinction is the
    point: muse splits the frown-muscle envelope by timescale, sending brief
    elevations to valence and the sustained level to tension, so a test that
    only ever holds the muscle down cannot see valence move.
    """
    rng = np.random.default_rng(seed)
    n = int(dur * FS)
    t = np.arange(n) / FS
    out = np.zeros((4, n), dtype=np.float32)
    gain = {0: 1 - asym, 1: 1 - asym, 2: 1 + asym, 3: 1 + asym}
    for c in range(4):
        out[c] = (alpha * gain[c] * np.sin(2 * np.pi * 10 * t + c)
                  + beta * np.sin(2 * np.pi * 20 * t + c)
                  + rng.standard_normal(n) * noise)
    amplitude = np.full(n, float(emg))
    for start_s, burst_dur_s, amp in emg_bursts:
        i0 = int(round(start_s * FS))
        i1 = min(n, i0 + int(round(burst_dur_s * FS)))
        amplitude[i0:i1] += float(amp)
    if np.any(amplitude > 0):
        hf = rng.standard_normal((2, n))
        spec = np.fft.rfft(hf, axis=-1)
        freqs = np.fft.rfftfreq(n, 1 / FS)
        spec[:, (freqs < 55) | (freqs > 110)] = 0
        hf = np.fft.irfft(spec, n, axis=-1)
        hf /= hf.std()
        out[1:3] += (amplitude * hf).astype(np.float32)
    return out
